import { type Metadata } from 'next';
import Link from 'next/link';
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import './global.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: undefined,
        variables: {
          colorPrimary: '#6c47ff',
          colorBackground: '#ffffff',
          colorInputBackground: '#f8fafc',
          colorInputText: '#1e293b',
          borderRadius: '0.5rem',
        },
        elements: {
          formButtonPrimary:
            'bg-[#6c47ff] hover:bg-[#5a3de0] text-white shadow-md hover:shadow-lg transition-all',
          card: 'shadow-xl',
          headerTitle: 'text-slate-800',
          headerSubtitle: 'text-slate-600',
          socialButtonsBlockButton:
            'border-slate-200 hover:bg-slate-50 transition-colors',
          formFieldInput:
            'border-slate-300 focus:border-[#6c47ff] focus:ring-[#6c47ff]',
          footerActionLink: 'text-[#6c47ff] hover:text-[#5a3de0]',
        },
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-slate-50 to-slate-100`}
        >
          <header className="w-full flex justify-between items-center px-6 py-4 bg-white/80 backdrop-blur-sm shadow-sm border-b border-slate-200">
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-semibold text-slate-800">Your App</h1>
            </div>
            <div className="flex items-center gap-4">
              <SignedIn>
                <nav className="flex items-center gap-4">
                  <Link
                    href="/"
                    className="text-slate-700 hover:text-[#6c47ff] font-medium text-sm sm:text-base transition-colors"
                  >
                    Todos
                  </Link>
                  <Link
                    href="/gallery"
                    className="text-slate-700 hover:text-[#6c47ff] font-medium text-sm sm:text-base transition-colors"
                  >
                    Gallery
                  </Link>
                </nav>
              </SignedIn>
              <SignedOut>
                <SignInButton mode="modal">
                  <button className="text-slate-700 hover:text-slate-900 font-medium text-sm sm:text-base px-4 py-2 transition-colors">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button className="bg-[#6c47ff] hover:bg-[#5a3de0] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-6 sm:px-8 cursor-pointer transition-colors shadow-md hover:shadow-lg">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <main className="w-full">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
