name = "backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Uncomment after creating your D1 database
# Run: pnpm wrangler d1 create your-database-name
# Then update these values with the output from the command above
#
# [[d1_databases]]
# binding = "DB"
# database_name = "your-database-name"
# database_id = "your-database-id"

# Development configuration
[dev]
port = 8787
